language: node_js

node_js:
 - lts/*

cache: npm

install:
 - npm install

env:
 - app_environment=$app_environment hp_zone_server_base_path=$hp_zone_server_base_path hp_zone_server_client_secret=$hp_zone_server_client_secret client_password_hash_cycle=$client_password_hash_cycle mongodb_atlas_connection_url=$mongodb_atlas_connection_url

deploy:
  provider: heroku
  skip_cleanup: true
  api_key: $HEROKU_TOKEN
  keep_history: true
  on:
    branch: master
